#define BIND_CAMERA 0
#define BIND_FRUSTUM 1
#define BIND_VERTEX 0
#define BIND_OBJECT 0
#define BIND_OBJECT_COUNT 1
#define BIND_OBJECT_COLLISION 2
#define BIND_OBJECT_MESHLET_ID 3
#define BIND_OBJECT_MESHLET_ID_COUNT 4
#define BIND_MESHLET 0
#define BIND_MESHLET_VERTEX 1
#define BIND_MESHLET_INDEX 2
#define BIND_MESHLET_CULLING 3

#define DEFAULT_UBO_LAYOUT 0
#define DEFAULT_VERTEX_LAYOUT 1
#define DEFAULT_LIGHT_LAYOUT 2
#define DEFAULT_SAMPLER_LAYOUT 3
#define DEFAULT_SHADOW_SAMPLER_LAYOUT 4
#define DEFAULT_CASCADED_UBO_LAYOUT 5
#define DEFAULT_OBJECT_LAYOUT 6
#define DEFAULT_MESHLET_LAYOUT 7

#define DEFAULT_DESCRIPTOR_SET_LAYOUT_COUNT 7
#define MESH_DESCRIPTOR_SET_LAYOUT_COUNT 8
#define SHAPE_DESCRIPTOR_SET_LAYOUT_COUNT 2

#define VERTEX_PIPELINE_ID 0
#define SHAPE_PIPELINE_ID 1
#define MESH_PIPELINE_ID 6
#define TEXT_PIPELINE_ID 7
#define LIGHT_PIPELINE_ID 4
#define TERRAIN_PIPELINE_ID 8
#define COLLISION_PIPELINE_ID 3

#define CULL_MODE_ID 0
#define CULL_BACKFACE 1
#define CULL_FRUSTUM 2
#define CULL CULL_BACKFACE | CULL_FRUSTUM
