#define CULL_MODE_ID 0
#define CULL_NONE 0
#define CULL_BACKFACE 1
#define CULL_FRUSTUM 2
#define CULL_ALL CULL_BACKFACE | CULL_FRUSTUM

#define MESH_PIPELINE_ID 0
#define TEXT_PIPELINE_ID 1
#define SHAPE_PIPELINE_ID 2
