#version 460

layout(push_constant) uniform Push {
    uint sType;
    vec3 color;
} push;

struct Projection
{
    vec2 pos1;
    vec2 pos2;
};

struct Object{
    mat4 model;
};

layout(std140, set = 0, binding = 0) buffer ObjectBuffer {
    Object objects[];
} objectBuffer;

layout(std140, binding = 1) readonly buffer SSBOIn
{
    Projection projectionsIn[];
};

layout(std140, binding = 2) buffer SSBOOut
{
    Projection projectionsOut[];
};

void main()
{
    
}