#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_scalar_block_layout: require

#include "mesh.h"

layout(local_size_x = TASK_WORKGROUP, local_size_y = 1, local_size_z = 1) in;
struct Projection
{
    vec2 pos1;
    vec2 pos2;
};

layout(std430, set = 0, binding = 1) buffer ObjectBuffer
{
    Object objects[];
};

layout(std430, set = 0, binding = 2) buffer countBuffer
{
    uint objectCount;
    uint collidedCount;
};

layout(scalar, set = 0, binding = 3) buffer collisionBuffer
{
    CollisionData collisions[];
};

bool AABBTest(vec3 overlap)
{
    return overlap.x >= 0. && overlap.y >= 0. && overlap.z >= 0.;
}

void main()
{
    uint pos = gl_GlobalInvocationID.x;
    if (pos > objectCount)
        return;
    if (pos == 0.)
    {
        collidedCount = 0;
    }
    barrier();

    for (uint i = 0; i < pos; i++)
    { 
        float r = objects[i].radius + objects[pos].radius;
        vec3 relativePos = objects[i].center - objects[pos].center;
        if (dot(relativePos, relativePos) <= r * r)
        {
            vec3 overlap = (objects[i].halfVolume.xyz + objects[pos].halfVolume.xyz) - abs(relativePos);
            if (AABBTest(overlap))
            {
                uint index = atomicAdd(collidedCount, 1);
                collisions[index].pair = uvec2(pos, i);
                collisions[index].normal = normalize(relativePos);
                collisions[index].penetration = length(overlap);
            }
        }
    }
    barrier();
}