#version 460
#extension GL_GOOGLE_include_directive : require

#include "mesh.h"

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;
struct Projection
{
    vec2 pos1;
    vec2 pos2;
};

layout(std430, set = 0, binding = 1) buffer ObjectBuffer
{
    Object objects[];
};

layout(std430, set = 0, binding = 2) buffer countBuffer
{
    uint objectCount;
};
/*
layout(std140, binding = 2) buffer SSBOOut
{
    uvec2 collidedPairs[];
};
*/
shared uint collidedCount;

void main()
{
    uint pos = gl_GlobalInvocationID.x;
    collidedCount = 0;
    barrier();
    if (pos > objectCount)
        return;

    for (uint i = 0; i < pos; i++)
    { 
        float r = objects[i].radius + objects[pos].radius;
        if (distance(objects[i].center, objects[pos].center) < r)
        {
            uint index = atomicAdd(collidedCount, 1);
            //collidedPairs[index] = uvec2(i, pos);
            objects[i].transform[3].w = 2.0;
            objects[pos].transform[3].w = 2.0;
        }
        else
        {
            objects[i].transform[3].w = 3.0;
            objects[pos].transform[3].w = 3.0;
        }
    }
}