#version 460

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D positionSampler;
layout(set = 0, binding = 1) uniform sampler2D normalSampler;
layout(set = 0, binding = 2) uniform sampler2D albedoSampler;
layout(set = 0, binding = 3) uniform sampler2D depthSampler;

layout(set = 0, binding = 4) uniform writeonly image2D outImage;

void main()
{
    vec2 pos = vec2(gl_GlobalInvocationID.xy);
    vec2 imageSize = vec2(textureSize(positionSampler, 0));
    vec2 uv = pos / imageSize;
    vec4 position = texture(positionSampler, uv);
    vec4 normal = texture(normalSampler, uv);
    vec4 albedo = texture(albedoSampler, uv);
    imageStore(outImage, ivec2(pos), albedo);
}