AnAControls = static_library('AnAControls', ['Button.cpp', 'ItemPresenter.cpp', 'SceneView.cpp', 'TextBlock.cpp',
    'Control.cpp', 'ItemsPresenter.cpp', 'Slider.cpp', 'TextBox.cpp', 'ToggleSwitch.cpp', 'ObjectView.cpp',
    'Grid.cpp', 'ListView.cpp', 'StackView.cpp', 'StackPanel.cpp', 'PageView.cpp', 'ComboBox.cpp',
    'Scrollable.cpp'],
    dependencies: [vulkan_dep, sdl3_dep],
    cpp_args: cflags
    )
