AnAControls = static_library('AnAControls', ['Button.cpp', 'ItemPresenter.cpp', 'SceneView.cpp', 'TextBlock.cpp',
    'Control.cpp', 'ItemsPresenter.cpp', 'Slider.cpp', 'TextBox.cpp', 'ToggleSwitch.cpp',
    'Grid.cpp', 'ListView.cpp', 'StackPanel.cpp', 'PageView.cpp'], 
    dependencies: [vulkan_dep, glfw_dep, glslang_dep]
    )