AnAControls = static_library('AnAControls', ['Button.cpp', 'ItemPresenter.cpp', 'Scene.cpp', 'TextBlock.cpp',
    'Control.cpp', 'ItemsPresenter.cpp', 'Slider.cpp', 'TextBox.cpp',
    'Grid.cpp', 'ListView.cpp', 'StackPanel.cpp'], 
    cpp_args: ['-std=c++23'],
    dependencies: [vulkan_dep, glfw_dep]
    )